# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Talk' do
pod 'EaseMobSDK', '~> 2.2.6'
pod 'SDWebImage', '~> 3.8.1'
pod 'SwiftDate', '~> 3.0.8'
pod 'AsyncSwift', '~> 1.7.3'
end

